/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TraceRoute;

import TraceRoute.osm.OpenStreetMap;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        try {
            OpenStreetMap osm = new OpenStreetMap("../maps/cyclable.osm.pbf");
            osm.visualiseTree();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
